curl -X POST localhost:5000/post_json \
    -H "Content-type: application/json" \
    -d "{ \
        \"min_wave\" : 1900, \
        \"max_wave\" : 2300, \
        \"molecule\" : \"CO\", \
        \"pressure\" : 0.01, \
        \"resolution\" : 1, \
        \"num_scan\" : 1, \
        \"zero_fill\" : 0, \
        \"source\" : \"tungsten\", \
        \"beamsplitter\" : \"AR_ZnSe\", \
        \"cell_window\" : \"CaF2\", \
        \"detector\" : \"MCT\" \
    }"
